### PR TITLE
Fix Performance Degradation

### LINKED ISSUE #12: Performance Issues on Higher Accuracies
Split from #10

### PR DESCRIPTION
**Pull request by LuaRook**
This pull-request closes #12 and resolves issues with performance degradation at higher accuracies. This is fixed by using ``OverlapParams``.

### CODE REVIEW

File: src/ZoneDaemon/init.lua [hunk 1]
```diff
@@ -172,9 +198,14 @@ function ZoneDaemon.new(container: {BasePart} | Instance, accuracy: typeof(ZoneD
 		if self.Group then
 			canZonesInGroupIntersect = self.Group:CanZonesTriggerOnIntersect()
 		end
+
+		local overlapParams = OverlapParams.new()
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:202]: Creating an OverlapParams object every single tick seems a bit strange, but considering GC and how the characters array is modified in a higher scope, I'll allow it.

File: src/ZoneDaemon/init.lua [hunk 2]
```diff
@@ -274,18 +309,19 @@ function ZoneDaemon.new(container: {BasePart} | Instance, accuracy: typeof(ZoneD
 				table.insert(currentPlayers, Player)
 			end
 		end
-		
-		for player, dict in pairs(selectedElement) do
-            if not self._currentElements[player] then
-                self._currentElements[player] = {}
-            end
+
+		for player: Player, dict in pairs(selectedElement) do
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:313]: This is explicitly defined in the selectedElement object, but I'll allow it.

File: src/ZoneDaemon/init.lua [hunk 3]
```diff
@@ -367,8 +404,10 @@ function ZoneDaemon:ListenToElementChangesForPlayer(elementName: string, player:
 	if self._elementQueryListeners[player][elementName] then
 		self._elementQueryListeners[player][elementName]:Destroy()
 	end
-	local signal = Signal.new()
+	
+	local signal = self._trove:Construct(Signal)
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:408]: Good catch on mem leak

File: src/ZoneDaemon/init.lua (hunk 1 above)
Comment (EncodedVenom) [reply src/ZoneDaemon/init.lua:202]: I also kinda want to tinker with the thought of having overlapParams defined in the context of the Zone class so that the user may have other things (not just players) activate the zone. Perhaps projectiles in their use case.

**Review by EncodedVenom — CHANGES_REQUESTED** [review]
I'm going to request that you move overlapParams in the context of the zone object as well as construct it on the `ZoneDaemon.new` call. Resolving FilterDescendantsInstances may be a bit tricky, but my generalized solution for this involves:

Creating a global overlapParams object. If the overlapParams object passed in an additional constructor argument into `ZoneDaemon.new` is non-existent, replace it in `Tick` with the global object.

The global overlapParams object should also be modified by the event listeners.

File: src/ZoneDaemon/init.lua [hunk 4]
```diff
@@ -250,14 +254,15 @@ function ZoneDaemon.new(container: {BasePart} | Instance, accuracy: typeof(ZoneD
...
+
 		table.clear(self._interactingPartsArray)
 		self._interactingPartsArray = newParts
 
 		local currentPlayers = {}
 		local selectedElement: {[Player]: {dist: number, element: string | nil, elementValue: any}} = {}
-		
+
 		for _, part: BasePart in pairs(self._interactingPartsArray) do
+			print("Part:", part)
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:265]: Debug statement

File: src/ZoneDaemon/init.lua [hunk 5]
```diff
@@ -1,4 +1,4 @@
-local Signal = require(script.Signal)
+local Signal = require(script..Signal)
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:1]: Yikes...

File: src/ZoneDaemon/init.lua [hunk 6]
```diff
@@ -466,4 +471,12 @@ function ZoneDaemon:GetPlayers(): Array<Player>
 	return self._interactingPlayersArray
 end
 
+function ZoneDaemon:SetParams(overlapParams: OverlapParams | string): nil
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:474]: OverlapParams isn't a string? Adjust this to OverlapParams | nil, and then blindly set it as it doesn't need an if statement.

File: src/ZoneDaemon/init.lua [hunk 7]
```diff
@@ -199,13 +202,14 @@ function ZoneDaemon.new(container: {BasePart} | Instance, accuracy: typeof(ZoneD
...
-		overlapParams.FilterType = Enum.RaycastFilterType.Whitelist
+		local overlapParams = if self._overrideParams then self._overrideParams else ZoneDaemon.OverlapParams
+		if overlapParams == ZoneDaemon.OverlapParams then
+			overlapParams.FilterDescendantsInstances = Characters
+		end
 
 		for _, part: Part in pairs(self._containerParts) do
 			if part.Shape == Enum.PartType.Ball then
-				for _, newPart in pairs(workspace:GetPartBoundsInRadius(part.Position, part.Size.X, overlapParams)) do
+				for _, newPart in pairs(workspace:GetPartBoundsInRadius(part.Position, part.Size.X, ZoneDaemon.OverlapParams)) do
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:212]: Should change `ZoneDaemon.OverlapParams` to `if self._overrideParams then self._overrideParams else ZoneDaemon.OverlapParams`

File: src/ZoneDaemon/init.lua [hunk 8]
```diff
@@ -215,7 +219,7 @@ function ZoneDaemon.new(container: {BasePart} | Instance, accuracy: typeof(ZoneD
 					intersectionPart[newPart] = part
 				end
 			else
-				for _, newPart in pairs(workspace:GetPartsInPart(part, overlapParams)) do
+				for _, newPart in pairs(workspace:GetPartsInPart(part, OverlapParams)) do
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:222]: Same issue as line 212

File: src/ZoneDaemon/init.lua [hunk 9]
```diff
@@ -199,13 +202,14 @@ function ZoneDaemon.new(container: {BasePart} | Instance, accuracy: typeof(ZoneD
 			canZonesInGroupIntersect = self.Group:CanZonesTriggerOnIntersect()
 		end
 
-		local overlapParams = OverlapParams.new()
-		overlapParams.FilterDescendantsInstances = Characters
-		overlapParams.FilterType = Enum.RaycastFilterType.Whitelist
+		local overlapParams = if self._overrideParams then self._overrideParams else ZoneDaemon.OverlapParams
+		if overlapParams == ZoneDaemon.OverlapParams then
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:206]: Seems a bit odd to assign at tick but I'll allow it.

File: src/ZoneDaemon/init.lua [hunk 10]
```diff
@@ -199,13 +202,14 @@ function ZoneDaemon.new(container: {BasePart} | Instance, accuracy: typeof(ZoneD
 			canZonesInGroupIntersect = self.Group:CanZonesTriggerOnIntersect()
 		end
 
-		local overlapParams = OverlapParams.new()
-		overlapParams.FilterDescendantsInstances = Characters
-		overlapParams.FilterType = Enum.RaycastFilterType.Whitelist
+		local overlapParams = if self._overrideParams then self._overrideParams else ZoneDaemon.OverlapParams
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:205]: This is the variable needed on lines 212 and 222, not `OverlapParams`. Keep capitalization in mind.

**Review by EncodedVenom — CHANGES_REQUESTED** [review]
Some things need adjustments.

File: src/ZoneDaemon/init.lua [hunk 11]
```diff
@@ -172,9 +201,15 @@ function ZoneDaemon.new(container: {BasePart} | Instance, accuracy: typeof(ZoneD
...
+
+		local overlapParams = if self._overrideParams then self._overrideParams else ZoneDaemon.OverlapParams
+		if overlapParams == ZoneDaemon.OverlapParams then
+			overlapParams.FilterDescendantsInstances = Characters
+		end
+
 		for _, part: Part in pairs(self._containerParts) do
 			if part.Shape == Enum.PartType.Ball then
-				for _, newPart in pairs(workspace:GetPartBoundsInRadius(part.Position, part.Size.X)) do
+				for _, newPart in pairs(workspace:GetPartBoundsInRadius(part.Position, part.Size.X, ZoneDaemon.OverlapParams)) do
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:212]: This should be using the variable defined on line 205.

File: src/ZoneDaemon/init.lua [hunk 12]
```diff
@@ -184,7 +219,7 @@ function ZoneDaemon.new(container: {BasePart} | Instance, accuracy: typeof(ZoneD
 					intersectionPart[newPart] = part
 				end
 			else
-				for _, newPart in pairs(workspace:GetPartsInPart(part)) do
+				for _, newPart in pairs(workspace:GetPartsInPart(part, ZoneDaemon.OverlapParams)) do
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:222]: Same story.

**Review by EncodedVenom — CHANGES_REQUESTED** [review]
You left out the override specified on line 205.

File: src/ZoneDaemon/init.lua [hunk 13]
```diff
@@ -471,11 +470,11 @@ function ZoneDaemon:GetPlayers(): Array<Player>
 	return self._interactingPlayersArray
 end
 
-function ZoneDaemon:SetParams(overlapParams: OverlapParams | string): nil
-	if typeof(overlapParams) == "string" then
-		self._overrideParams = nil
-	else
+function ZoneDaemon:SetParams(overlapParams: OverlapParams | nil): nil
+	if overlapParams then
```
Comment (EncodedVenom) [inline src/ZoneDaemon/init.lua:474]: No need for an if statement.

**Review by EncodedVenom — CHANGES_REQUESTED** [review]

**Comment by EncodedVenom** [comment]
Once the extraneous if-statement is removed I'll merge

**Review by EncodedVenom — APPROVED** [review]
